wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.17
    framework: sklearn
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.10.2
    start_time: 1653949986
    t:
      1:
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 2
      4: 3.10.2
      5: 0.12.17
      8:
      - 1
      - 5
